version: "3"
services:
  db:
    image: postgres:13.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbadmin
      - POSTGRES_DB=quizappdb
    volumes:
      - ./docker-local/postgres-data:/var/lib/postgresql/data
    networks:
      - quizapp_net

  backend:
    image: node:15.14.0-alpine3.13
    restart: always
    environment:
      - NODE_ENV=dev
      - PORT=8000
      - ACCESS_JWT_SECRET=ACCESS_TOP_SECRET
      - REFRESH_JWT_SECRET=REFRESH_TOP_SECRET
      - DB_URI=postgresql://dbadmin:dbadmin@db:5432/quizappdb
    volumes:
      - ./QuizappBackend:/app
      - /app/node_modules
    entrypoint: "/app/entrypoint.sh"
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - quizapp_net

  web:
    image: node:15.14.0-alpine3.13
    restart: always
    environment:
      - NODE_ENV=dev
      - PORT=3000
    volumes:
      - ./quizappwebadmin:/app
      - /app/node_modules
    entrypoint: "/app/entrypoint.sh"
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - quizapp_net

  webserver:
    image: nginx:mainline-alpine
    ports:
      - 80:80
    volumes:
      - ./docker-local/nginx/fb.conf:/etc/nginx/conf.d/default.conf
      - ./docker-local/nginx/logs:/var/log/nginx
    depends_on:
      - web
      - backend
    networks:
      - quizapp_net

networks:
  quizapp_net:
    driver: bridge
