version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Install node modules
          command: cd quizapp && yarn install
      - run:
          name: Build for production
          command: cd quizapp && yarn build
      - run:
          name: fix host authenticity for production server
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: installing rsync
          command: sudo apt-get install rsync
      - run:
          name: rsyncing build to production
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              cd quizapp/build && rsync . -avc -e ssh $SSH_USERNAME@$SSH_HOST:/var/www/quizapp
            else
              echo "not master branch, dry run only"
            fi

workflows:
    build-and-test:
      jobs:
        - build-and-deploy