version: "3"
services:
  db:
    image: postgres:13.2-alpine
    restart: always
    container_name: db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbadmin
      - POSTGRES_DB=quizappdb
    volumes:
      - ./docker-local/postgres-data:/var/lib/postgresql/data
    networks: 
    - quizapp_net

  backend:
    image: node:15.7.0-alpine3.12
    restart: always
    container_name: backend-container
    environment:
      - NODE_ENV=dev
      - PORT=8000
      - ACCESS_JWT_SECRET=ACCESS_TOP_SECRET
      - REFRESH_JWT_SECRET=REFRESH_TOP_SECRET
      - DB_URI=postgresql://dbadmin:dbadmin@db:5432/quizappdb
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: "/app/entrypoint.sh"
    ports:
      - 8000:8000
    depends_on: 
      - db
    networks: 
      - quizapp_net

networks:
  quizapp_net:
    driver: bridge
